[package]
name = "pelican_ui"
version = "0.1.0"
authors = ["Ella Mae <ellaammae@email.com>"]
edition = "2021"
description = "A modern UI/UX toolkit optimized for the RAMP stack."
license = "MIT OR Apache-2.0"
repository = "https://github.com/EllaCouch20/pelican_ui"
readme = "README.md"
keywords = ["ui", "ux", "ramp", "rust", "component"]
categories = ["gui", "visualization", "rendering", "development-tools::ui"]
documentation = "https://docs.rs/pelican-ui"
homepage = "https://github.com/EllaCouch20/pelican-ui"

[lib]
name = "pelican_ui"
path = "src/lib.rs"

[dependencies]
rust_on_rails = {path = "../rust_on_rails"}
qrcode = "0.14.1"
uuid = { version = "1.16.0", features = ["v4"] }
dyn-clone = "1.0.19"