[package]
name = "pelican_ui"
version = "0.1.0"
edition = "2021"

[lib]
name = "pelican_ui"
path = "src/lib.rs"

[dependencies]
rust_on_rails = {path = "../rust_on_rails"}
qrcode = "0.14.1"
once_cell = "1.20.3"
