[package]
name = "pelican_ui"
version = "0.1.0"
edition = "2021"

[lib]
name = "pelican_ui"
path = "src/lib.rs"

[dependencies]
rust_on_rails = {path = "../rust_on_rails"}
qrcode = "0.14.1"
once_cell = "1.20.3"
nsvg = "0.5.1"
image = "0.25.5"
fast_image_resize = "5.1.2"
uuid = { version = "1.16.0", features = ["v4"] }
